---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check page
      ansible.builtin.uri:
        url: "http://localhost:8095"
        status_code: "200"
        timeout: "300"
        return_content: true
      async: "300"
      poll: "10"
      register: result
      until: result.status == 200
      retries: 30

    - name: check result
      ansible.builtin.fail:
      when: "'crowd' not in result.content"
